### ISSUE TITLE
When we do 'cargo test' the doc tests throw an error

### ISSUE THREAD

**Issue by vivek378521** [uds5501/Phi-Accrual-Detector#1]
The error

> Doc-tests phi-accrual-detector

> running 2 tests
> test src/lib.rs - (line 6) ... FAILED
> test src/lib.rs - (line 52) ... ok
> 
> failures:
> 
> ---- src/lib.rs - (line 6) stdout ----
> error[E0599]: no method named `insert` found for struct `Arc<Detector>` in the current scope
>   --> src/lib.rs:29:23
>    |
> 25 |         self.detector.insert(current_time).await.expect("Some panic occurred");
>    |                       ^^^^^^ method not found in `Arc<Detector>`
>    |
>    = help: items from traits can only be used if the trait is in scope
> help: the following trait is implemented but not in scope; perhaps add a `use` for it:
>    |
> 2  + use crate::phi_accrual_detector::PhiInteraction;
>    |
> 
> error[E0599]: no method named `last_arrived_at` found for struct `Arc<Detector>` in the current scope
>   --> src/lib.rs:34:44
>    |
> 30 |        let last_arrived_at = self.detector.last_arrived_at().await.expect("Some panic occurred");
>    |                                            ^^^^^^^^^^^^^^^ method not found in `Arc<Detector>`
>    |
>    = help: items from traits can only be used if the trait is in scope
> help: the following trait is implemented but not in scope; perhaps add a `use` for it:
>    |
> 2  + use crate::phi_accrual_detector::PhiInteraction;
>    |
> 
> error[E0599]: no method named `phi` found for struct `Arc<Detector>` in the current scope
>   --> src/lib.rs:36:32
>    |
> 32 |        let phi = self.detector.phi(current_time).await.unwrap();
>    |                                ^^^ method not found in `Arc<Detector>`
>    |
>    = help: items from traits can only be used if the trait is in scope
> help: the following trait is implemented but not in scope; perhaps add a `use` for it:
>    |
> 2  + use crate::phi_accrual_detector::PhiInteraction;
>    |
> 
> error: aborting due to 3 previous errors
> 
> For more information about this error, try `rustc --explain E0599`.
> Couldn't compile the test.
> 
> failures:
>     src/lib.rs - (line 6)
> 
> test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.37s
> 
> error: doctest failed, to rerun pass `--doc`

**Comment by vivek378521** [comment]
If we remove the commented portion of the code from the file, the all tests successfully pass.

**Comment by uds5501** [comment]
I think we need to complete the entire example, just removing the comments won't work

**Comment by vivek378521** [comment]
My bad, I have fixed the error, should I raise a PR?

![Screenshot 2024-04-23 at 10 53 27 AM](https://github.com/uds5501/Phi-Accrual-Detector/assets/29369111/e1c33d73-1884-4dd4-9590-da11a13f13b1)

**Comment by uds5501** [comment]
Yes please! Will review

**Comment by uds5501** [comment]
Fixed in https://github.com/uds5501/Phi-Accrual-Detector/pull/2
